{
  # mt = media type. 2 indicates podcasts
  arts:                         "https://itunes.apple.com/us/genre/podcasts-arts/id1301?mt=2",
  business:                     "https://itunes.apple.com/us/genre/podcasts-business/id1321?mt=2",
  comedy:                       "https://itunes.apple.com/us/genre/podcasts-comedy/id1303?mt=2",
  education:                    "https://itunes.apple.com/us/genre/podcasts-education/id1304?mt=2",
  games_and_hobbies:            "https://itunes.apple.com/us/genre/podcasts-games-hobbies/id1323?mt=2",
  government_and_organizations: "https://itunes.apple.com/us/genre/podcasts-government-organizations/id1325?mt=2",
  health:                       "https://itunes.apple.com/us/genre/podcasts-health/id1307?mt=2",
  kids_and_family:              "https://itunes.apple.com/us/genre/podcasts-kids-family/id1305?mt=2",
  music:                        "https://itunes.apple.com/us/genre/podcasts-music/id1310?mt=2",
  news_and_politics:            "https://itunes.apple.com/us/genre/podcasts-news-politics/id1311?mt=2",
  religion_and_spirituality:    "https://itunes.apple.com/us/genre/podcasts-religion-spirituality/id1314?mt=2",
  science_and_medicine:         "https://itunes.apple.com/us/genre/podcasts-science-medicine/id1315?mt=2",
  society_and_culture:          "https://itunes.apple.com/us/genre/podcasts-society-culture/id1324?mt=2",
  sports_and_recreation:        "https://itunes.apple.com/us/genre/podcasts-sports-recreation/id1316?mt=2",
  tv_and_film:                  "https://itunes.apple.com/us/genre/podcasts-tv-film/id1309?mt=2",
  technology:                   "https://itunes.apple.com/us/genre/podcasts-technology/id1318?mt=2"
}
